# fly.toml file generated for tgbotderbl on 2023-03-02T03:21:23Z

app = "chatgpt-bot-rbl"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
image = "ghcr.io/rabilrbl/chatgpt-bot:latest"

[env]

[experimental]
  auto_rollback = true

[[services]]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

# Dummy port as services.ports is required for fly.toml
[[services.ports]]
handlers = ["http"]
port = 80

[deploy]
  strategy = "immediate"